name: hotel
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  mask_text_input_formatter: ^2.5.0
  get_it: ^7.6.4
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Bold.ttf
        - asset: assets/fonts/SFProDisplay-Light.ttf
        - asset: assets/fonts/SFProDisplay-Medium.ttf
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
